//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.Comments = new HashSet<Comment>();
            this.DatHangCTs = new HashSet<DatHangCT>();
            this.ThamGias = new HashSet<ThamGia>();
        }
    
        public int SachID { get; set; }
        public string TenSach { get; set; }
        public double GiaBan { get; set; }
        public string MaChuDe { get; set; }
        public int NhaXuatBanID { get; set; }
        public string MoTa { get; set; }
        public string HinhBia { get; set; }
        public int SoTrang { get; set; }
        public int TrongLuong { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
        public int SoLanXem { get; set; }
        public int SoLuongBan { get; set; }
        public bool HetHang { get; set; }
    
        public virtual ChuDe ChuDe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatHangCT> DatHangCTs { get; set; }
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThamGia> ThamGias { get; set; }
    }
}
